export function Model() {
  return (
    <section>
      <div className="page-head"><div><h1>Model Performance</h1><p>Evaluation output from generated model artifacts</p></div></div>
      <div className="panel prose">
        <h2>Isolation Forest Baseline</h2>
        <p>The demo model is trained on safe synthetic flow metadata and evaluated only to verify the pipeline. Real performance must be measured on held-out CICIDS2017 labels.</p>
        <table>
          <thead><tr><th>Model</th><th>Precision</th><th>Recall</th><th>F1</th><th>False Positive Rate</th></tr></thead>
          <tbody><tr><td>Isolation Forest</td><td>Generated by scripts/evaluate.py</td><td>Generated</td><td>Generated</td><td>Generated</td></tr></tbody>
        </table>
        <p>Accuracy alone can be misleading for imbalanced security datasets. False positives matter because analysts must spend time investigating each alert.</p>
      </div>
    </section>
  );
}

